// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8K3GqYpbilcmPQvYcjsSyLuLyr_HrGaY',
    appId: '1:502945722675:web:20931819b19db38a644e46',
    messagingSenderId: '502945722675',
    projectId: 'expensetracker-sk',
    authDomain: 'expensetracker-sk.firebaseapp.com',
    storageBucket: 'expensetracker-sk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAv67ZkmOPh7Hw4fXVc5bb5RK_clqnAI',
    appId: '1:502945722675:android:8222965edf6cbaa9644e46',
    messagingSenderId: '502945722675',
    projectId: 'expensetracker-sk',
    storageBucket: 'expensetracker-sk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNiv6W_CJMY41zz5QPANit7FJraxfD7Q',
    appId: '1:502945722675:ios:eb8274faee115820644e46',
    messagingSenderId: '502945722675',
    projectId: 'expensetracker-sk',
    storageBucket: 'expensetracker-sk.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGNiv6W_CJMY41zz5QPANit7FJraxfD7Q',
    appId: '1:502945722675:ios:eb8274faee115820644e46',
    messagingSenderId: '502945722675',
    projectId: 'expensetracker-sk',
    storageBucket: 'expensetracker-sk.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8K3GqYpbilcmPQvYcjsSyLuLyr_HrGaY',
    appId: '1:502945722675:web:c0037fb80b5520bf644e46',
    messagingSenderId: '502945722675',
    projectId: 'expensetracker-sk',
    authDomain: 'expensetracker-sk.firebaseapp.com',
    storageBucket: 'expensetracker-sk.firebasestorage.app',
  );
}