name: Build Flutter APK

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.5'  # ✅ DO NOT add `channel`, `architecture`, etc.

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build artifacts
        run: flutter clean

      - name: Build release APK (split per ABI)
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk
