name: Build My App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.5'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Clean Previous Builds
        run: flutter clean

      - name: Run Flutter Build
        run: flutter build apk --release --split-per-abi
